### ISSUE TITLE
how to - announcement features

### ISSUE THREAD

**Issue by gchan123** [thenhkid/rapidRegistryBugs#5]
Where are these?
a) ability to set max # of announcements to be displayed 
e - 2) ability to BOLD an announcement - I can do it with <b> tags but not sure if we expect users to know that or there is a separate function
g) ability to prioritize display order of documents; 
h)ability to size/position announcements window based on other landing page content.

**Comment by thenhkid** [comment]
I left these out because I was not sure of them. I will push this modulei
without them and specifically point them out to Mike as to how he wants to
proceed with them after he sees the layout.

—
Thank You!
Chad McCue

**Comment by gchan123** [comment]
cool.  thanks!
